export const SCHEDULED_QUEUE_PROCESS_NAME = 'REDIS_PROCESS';
export const SCHEDULED_QUEUE_NAME = 'SCHEDULED__REDIS__KAFKA';
export const SCHEDULED_FAILED_RETRY_CRON = '*/30 * * * * *';
export const SCHEDULED_FAILED_RETRY_CRON_MAXIMUM_JOB_RETRY_LENGTH = 10000;
export const REQUEST_ID_HEADER = 'x-request-id';